---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: hello-world
          image: yusufkaratoprak/kubernetes-gosample:latest
          ports:
            - containerPort: 8090
