---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backends.stable.example.com
  annotations:
    servicebindingoperator.redhat.io/spec.host: 'binding:volumemount:attribute'
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: backends
    singular: backend
    kind: Backend
    shortNames:
      - bk
